#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/linux_amd64_ifort+mpi_ice_nas,v 1.19 2017/04/07 19:22:56 dfer Exp $
# $Name:  $

# Used to run the testreport on pleiades with:
# module load comp-intel/2016.2.181 mpi-sgi/mpt.2.14r19 netcdf/4.0
# works on all types of nodes 

FC=ifort
F90C=ifort
CC=icc

DEFINES='-DALLOW_USE_MPI -DPLEIADES_LUSTRE_OPT -DPLEIADES_LUSTRE_OPT2 -DPLEIADES_LUSTRE_OPT3 -DALWAYS_USE_MPI -DWORDLENGTH=4 -DINTEL_COMMITQQ'
CPP='/lib/cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'
OMPFLAG='-openmp'
CFLAGS='-g -fPIC'
LDADD='-shared-intel'

#20200713
LIBS='-lmpi -L/nasa/netcdf/4.4.1.1_mpt/lib -lnetcdf'
INCLUDES='-I/nasa/netcdf/4.4.1.1_mpt/include'

#before 20200713
#LIBS='-L/nasa/sgi/mpt/2.15r20/lib -lmpi -L/nasa/netcdf/4.4.1.1_mpt/lib -lnetcdf'
#INCLUDES='-I/nasa/sgi/mpt/2.15r20/include -I/nasa/netcdf/4.4.1.1_mpt/include'
#INCLUDEDIRS='/nasa/sgi/mpt/2.15r20/include'
#- used for parallel (MPI) DIVA
#MPIINCLUDEDIR='/nasa/sgi/mpt/2.11r13/include'
#MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'

#NOOPTFLAGS='-O1 -fp-model precise'
NOOPTFLAGS='-O0'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS="$FFLAGS -fPIC -W0 -WB -convert big_endian -assume byterecl -align -mcmodel medium"
    FOPTIM='-g -O2 -ipo -fp-model precise -xCORE-AVX2 -traceback -ftz'
    #FOPTIM='-g -O0 -fp-model strict -traceback -ftz -debug full -check uninit,bounds -fpe0 -init=arrays -init=snan -ftrapuv'
    F90FLAGS=$FFLAGS
    F90OPTIM=$FOPTIM
    NOOPTFILES='seaice_growth.F calc_oce_mxlayer.F fizhi_lsm.F fizhi_clockstuff.F ini_parms.F'
else
    #  Try to follow IEEE-754
    FFLAGS="$FFLAGS -fPIC -W0 -WB -convert big_endian -assume byterecl -noalign -mcmodel medium"
    FOPTIM='-O0'
fi
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

#- For really big executable (> 2 GB), uncomment following 2 lines
#FFLAGS="$FFLAGS -mcmodel=medium -shared-intel"
#CFLAGS="$CFLAGS -mcmodel=medium -shared-intel"
