#!/bin/bash
#
# eadd - ECCO Ancillary Data Download
#

# configuration (perhaps cfg/ENV at some point):
v=4; r=4
rooturl="https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/ECCO_L4_ANCILLARY_DATA_V${v}R${r}"

usage() {
    echo "$(basename $0) - ECCO V${v}r${r} ancillary data download, extract and, optionally, clean up"
    echo "usage: $(basename $0) [-u username] [-p password] [-k]"
    echo "where:"
    echo "    -u    NASA Earthdata username (prompt if not provided)"
    echo "    -p    NASA Earthdata password (prompt if not provided)"
    echo "    -k    Keep downloaded tarfiles after extraction"
    echo "note: $(basename $0) is called by the eget utility"
}
version() { echo "1.0"; }

keep=no
while getopts ":u:p:hkv" opt; do
    case $opt in
        k  ) keep=yes ;;
        u  ) uname=$OPTARG ;;
        p  ) passwd=$OPTARG ;;
        h  ) usage
             exit 1 ;;
        v  ) version
             exit 1 ;;
        \? ) usage
             exit 1 ;;
    esac
done
shift $(($OPTIND-1))

if [ -z $uname ]; then
    read -rsep "NASA Earthdata username: " uname
    echo ""
fi

if [ -z $passwd ]; then
    read -rsep "NASA Earthdata password: " passwd
    echo ""
fi

declare -a targets=(
    "ancillary_data_doc_ECCO_V${v}r${r}.tar.gz"
    "ancillary_data_input_init_ECCO_V${v}r${r}.tar.gz"
    "ancillary_data_input_forcing_ECCO_V${v}r${r}.tar.gz"
    "ancillary_data_native_grid_files_ECCO_V${v}r${r}.tar.gz"
    "ancillary_data_data_constraints_ECCO_V${v}r${r}.tar.gz"
    "ancillary_data_misc_ECCO_V${v}r${r}.tar.gz"
)

for target in ${targets[@]}; do
    wget --user=${uname} --password=${passwd} ${rooturl}/${target}
    echo "$(basename $0): extracting files from ${target} ..."
    tar -xvf ${target}
    echo "$(basename $0): ... done extracting files from ${target}."
    if [ $keep = no ]; then
        echo "$(basename $0): keep archive files (-k) option not selected; removing ${target}."
        rm ${target}
    fi
done

