#!/bin/bash
#
# eget - download (get) ECCO and MITgcm source, configuration, and ancillary data
#

# configuration (perhaps cfg/ENV at some point):
v=4; r=4
mitgcmrepo=https://github.com/MITgcm/MITgcm.git
eccorepo=https://github.com/ECCO-GROUP/ECCO-v${v}-Configurations.git
branch=checkpoint66g

usage() {
    echo "$(basename $0) - download (get) ECCO V${v}r${r} and MITgcm source, configuration, and ancillary data"
    echo "usage: $(basename $0) [-u username] [-p password] [-k] [dir]"
    echo "where:"
    echo "    -u    NASA Earthdata username (prompt if not provided)"
    echo "    -p    NASA Earthdata password (prompt if not provided)"
    echo "    -k    Keep downloaded tarfiles after extraction"
    echo "    dir   Top-level working directory"
    echo "note: $(basename $0)calls the eadd utility for ECCO ancillary data download"
}
version() { echo "1.0"; }

nargs=1
keep=no
while getopts ":u:p:hkv" opt; do
    case $opt in
        k  ) keep=yes ;;
        u  ) uname=$OPTARG ;;
        p  ) passwd=$OPTARG ;;
        h  ) usage
             exit 1 ;;
        v  ) version
             exit 1 ;;
        \? ) usage
             exit 1 ;;
    esac
done
shift $(($OPTIND-1))

if [[ $# -ne $nargs ]]; then
    usage
    exit 1
fi

workingdir=$1

if [ -z $uname ]; then
    read -rsep "NASA Earthdata username: " uname
    echo ""
fi

if [ -z $passwd ]; then
    read -rsep "NASA Earthdata password: " passwd
    echo ""
fi

if mkdir $workingdir && cd $workingdir; then

    #
    # clone MITgcm source:
    #

    echo "$(basename $0): cloning git repository $mitgcmrepo..."
    git clone $mitgcmrepo -b $branch
    echo "$(basename $0): ...done cloning $(basename $mitgcmrepo)."

    #
    # clone ecco configurations:
    #

    echo "$(basename $0): cloning ecco v${v}r${r} configurations, $eccorepo..."
    git clone $eccorepo
    mkdir -p ECCOV${v}/release${r}
    cp -r "ECCO-v${v}-Configurations/ECCOv${v} Release ${r}/code" ECCOV${v}/release${r}/code
    cp -r "ECCO-v${v}-Configurations/ECCOv${v} Release ${r}/namelist" ECCOV${v}/release${r}/namelist
    echo "$(basename $0): ...done cloning $(basename $eccorepo)."

    #
    # download ecco ancillary data:
    #

    if cd ECCOV${v}/release${r} && mkdir input && cd input; then
        if [ $keep = yes ]; then
            eadd -u ${uname} -p ${passwd} -k
        else
            eadd -u ${uname} -p ${passwd}
        fi
    fi
fi

cd $cwd
